import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.js";

dotenv.config();

// ✅ Inline DB connection (no import from ./config/db.js)
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log(`✅ MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`❌ Error: ${error.message}`);
    process.exit(1);
  }
};

const products = [
  // --- WOMEN DRESSES ---
  {
    name: "Elegant Red Dress",
    brand: "Fashionista",
    description: "Elegant red dress with modern design and lightweight fabric.",
    price: 1999,
    discountPrice: 1799,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-2_xifhsw.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-2_xifhsw.jpg", alt: "Elegant Red Dress" }],
    gender: "Women",
    type: "Dress",
    style: "Party",
    season: "Summer",
    tags: ["Red", "Elegant", "Party"],
    sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 8 }, { size: "L", stock: 10 }],
    colors: [{ name: "Red", hex: "#FF0000", stock: 23 }],
    countInStock: 23,
    isFeatured: true,
    isBestseller: true,
    sku: "DRS-RED-001",
    weight: 500,
    dimensions: { length: 30, width: 20, height: 5 },
    meta: { title: "Elegant Red Dress", description: "Shop Elegant Red Dress for parties and summer." }
  },
  {
    name: "Classic Blue Dress",
    brand: "UrbanWear",
    description: "Classic blue dress for casual and formal settings.",
    price: 1799,
    discountPrice: 1499,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-2_xifhsw.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-2_xifhsw.jpg", alt: "Classic Blue Dress" }],
    gender: "Women",
    type: "Dress",
    style: "Casual",
    season: "All-Season",
    tags: ["Blue", "Casual", "Women"],
    sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 6 }, { size: "L", stock: 9 }],
    colors: [{ name: "Blue", hex: "#0000FF", stock: 19 }],
    countInStock: 19,
    isFeatured: false,
    isBestseller: true,
    sku: "DRS-BLU-002",
    weight: 480,
    dimensions: { length: 30, width: 20, height: 5 },
    meta: { title: "Classic Blue Dress", description: "Shop Classic Blue Dress for daily wear." }
  },
  {
    name: "Floral Summer Dress",
    brand: "TrendyLook",
    description: "Floral summer dress, light cotton fabric, perfect for hot days.",
    price: 1599,
    discountPrice: 1299,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-1_yup0je.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/dress-1_yup0je.jpg", alt: "Floral Summer Dress" }],
    gender: "Women",
    type: "Dress",
    style: "Casual",
    season: "Summer",
    tags: ["Floral", "Summer", "Casual"],
    sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 7 }, { size: "L", stock: 8 }],
    colors: [{ name: "Floral", hex: "#FFC0CB", stock: 21 }],
    countInStock: 21,
    isFeatured: true,
    isBestseller: false,
    sku: "DRS-FLR-003",
    weight: 420,
    dimensions: { length: 28, width: 20, height: 4 },
    meta: { title: "Floral Summer Dress", description: "Shop Floral Summer Dress, breathable cotton." }
  },
  {
    name: "Modern Black Dress",
    brand: "UrbanWear",
    description: "Modern black dress suitable for parties and casual wear.",
    price: 1899,
    discountPrice: 1599,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/dress-5_chq80v.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/dress-5_chq80v.jpg", alt: "Modern Black Dress" }],
    gender: "Women",
    type: "Dress",
    style: "Party",
    season: "All-Season",
    tags: ["Black", "Modern", "Women"],
    sizes: [{ size: "M", stock: 7 }, { size: "L", stock: 9 }, { size: "XL", stock: 6 }],
    colors: [{ name: "Black", hex: "#000000", stock: 22 }],
    countInStock: 22,
    isFeatured: true,
    isBestseller: true,
    sku: "DRS-BLK-004",
    weight: 490,
    dimensions: { length: 30, width: 20, height: 5 },
    meta: { title: "Modern Black Dress", description: "Trendy black dress for versatile occasions." }
  },
  {
    name: "Designer Printed Dress",
    brand: "Fashionista",
    description: "Designer printed dress with unique patterns.",
    price: 2099,
    discountPrice: 1899,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/dress-4_n7vn8y.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/dress-4_n7vn8y.jpg", alt: "Designer Printed Dress" }],
    gender: "Women",
    type: "Dress",
    style: "Casual",
    season: "All-Season",
    tags: ["Designer", "Printed", "Trendy"],
    sizes: [{ size: "S", stock: 6 }, { size: "M", stock: 5 }, { size: "L", stock: 7 }],
    colors: [{ name: "Multi", hex: "#AAAAAA", stock: 18 }],
    countInStock: 18,
    isFeatured: false,
    isBestseller: false,
    sku: "DRS-PRT-005",
    weight: 460,
    dimensions: { length: 28, width: 19, height: 4 },
    meta: { title: "Designer Printed Dress", description: "Trendy designer printed dress for women." }
  },

  // --- KIDS WEAR ---
  {
    name: "Kids Casual Outfit",
    brand: "KiddoStyle",
    description: "Lightweight casual outfit for kids, perfect for playtime.",
    price: 899,
    discountPrice: 799,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/kid-1_o2gzhk.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318658/kid-1_o2gzhk.jpg", alt: "Kids Casual Outfit" }],
    gender: "Kids",
    type: "Dress",
    style: "Casual",
    season: "Summer",
    tags: ["Kids", "Casual", "Play"],
    sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 7 }, { size: "L", stock: 6 }],
    colors: [{ name: "Yellow", hex: "#FFD700", stock: 18 }],
    countInStock: 18,
    isFeatured: false,
    isBestseller: true,
    sku: "KID-OUT-006",
    weight: 300,
    dimensions: { length: 20, width: 15, height: 3 },
    meta: { title: "Kids Casual Outfit", description: "Light and comfortable outfit for kids." }
  },
  {
    name: "Kids Party Dress",
    brand: "KiddoStyle",
    description: "Beautiful kids party dress with soft fabric.",
    price: 1099,
    discountPrice: 999,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-2_irgnq3.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-2_irgnq3.jpg", alt: "Kids Party Dress" }],
    gender: "Kids",
    type: "Dress",
    style: "Party",
    season: "All-Season",
    tags: ["Kids", "Party", "Cute"],
    sizes: [{ size: "S", stock: 4 }, { size: "M", stock: 5 }, { size: "L", stock: 7 }],
    colors: [{ name: "Pink", hex: "#FFC0CB", stock: 16 }],
    countInStock: 16,
    isFeatured: true,
    isBestseller: false,
    sku: "KID-PTY-007",
    weight: 320,
    dimensions: { length: 22, width: 16, height: 3 },
    meta: { title: "Kids Party Dress", description: "Adorable kids party wear." }
  },
  {
    name: "Kids Winter Wear",
    brand: "KiddoStyle",
    description: "Warm winter wear for kids, soft and cozy.",
    price: 1299,
    discountPrice: 1199,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-3_u7m5rm.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-3_u7m5rm.jpg", alt: "Kids Winter Wear" }],
    gender: "Kids",
    type: "Dress",
    style: "Casual",
    season: "Winter",
    tags: ["Kids", "Winter", "Warm"],
    sizes: [{ size: "S", stock: 3 }, { size: "M", stock: 6 }, { size: "L", stock: 5 }],
    colors: [{ name: "Blue", hex: "#1E90FF", stock: 14 }],
    countInStock: 14,
    isFeatured: true,
    isBestseller: true,
    sku: "KID-WNT-008",
    weight: 600,
    dimensions: { length: 28, width: 18, height: 5 },
    meta: { title: "Kids Winter Wear", description: "Warm and cozy winter outfit for kids." }
  },
  {
    name: "Kids Sports Outfit",
    brand: "KiddoStyle",
    description: "Sporty kids outfit for outdoor activities.",
    price: 999,
    discountPrice: 899,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-4_dh01gp.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/kid-4_dh01gp.jpg", alt: "Kids Sports Outfit" }],
    gender: "Kids",
    type: "Dress",
    style: "Sportswear",
    season: "All-Season",
    tags: ["Kids", "Sports", "Active"],
    sizes: [{ size: "S", stock: 5 }, { size: "M", stock: 6 }, { size: "L", stock: 7 }],
    colors: [{ name: "Green", hex: "#008000", stock: 18 }],
    countInStock: 18,
    isFeatured: false,
    isBestseller: false,
    sku: "KID-SPT-009",
    weight: 350,
    dimensions: { length: 22, width: 16, height: 4 },
    meta: { title: "Kids Sports Outfit", description: "Durable sports outfit for kids." }
  },

  // --- PANTS ---
  {
    name: "Slim Fit Denim Jeans",
    brand: "UrbanWear",
    description: "Slim fit denim jeans for casual and stylish look.",
    price: 1699,
    discountPrice: 1499,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/pant-1_enbxom.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318659/pant-1_enbxom.jpg", alt: "Slim Fit Denim Jeans" }],
    gender: "Men",
    type: "Jeans",
    style: "Casual",
    season: "All-Season",
    tags: ["Denim", "Jeans", "Men"],
    sizes: [{ size: "M", stock: 8 }, { size: "L", stock: 10 }, { size: "XL", stock: 6 }],
    colors: [{ name: "Blue", hex: "#0000FF", stock: 24 }],
    countInStock: 24,
    isFeatured: true,
    isBestseller: true,
    sku: "PNT-DNM-010",
    weight: 700,
    dimensions: { length: 40, width: 30, height: 5 },
    meta: { title: "Slim Fit Denim Jeans", description: "Classic slim fit denim jeans for men." }
  },
  {
    name: "Classic Chinos",
    brand: "Fashionista",
    description: "Classic chinos perfect for formal and casual occasions.",
    price: 1499,
    discountPrice: 1299,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318663/pant-2_fesrpu.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318663/pant-2_fesrpu.jpg", alt: "Classic Chinos" }],
    gender: "Men",
    type: "Pants",
    style: "Formal",
    season: "All-Season",
    tags: ["Chinos", "Formal", "Men"],
    sizes: [{ size: "M", stock: 7 }, { size: "L", stock: 8 }, { size: "XL", stock: 5 }],
    colors: [{ name: "Beige", hex: "#F5F5DC", stock: 20 }],
    countInStock: 20,
    isFeatured: false,
    isBestseller: true,
    sku: "PNT-CHN-011",
    weight: 650,
    dimensions: { length: 40, width: 30, height: 5 },
    meta: { title: "Classic Chinos", description: "Versatile chinos for men." }
  },
  {
    name: "Cargo Pants",
    brand: "TrendyLook",
    description: "Durable cargo pants for outdoor adventures.",
    price: 1599,
    discountPrice: 1399,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318665/pant-3_pojns8.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318665/pant-3_pojns8.jpg", alt: "Cargo Pants" }],
    gender: "Men",
    type: "Pants",
    style: "Casual",
    season: "All-Season",
    tags: ["Cargo", "Outdoor", "Men"],
    sizes: [{ size: "M", stock: 9 }, { size: "L", stock: 10 }, { size: "XL", stock: 7 }],
    colors: [{ name: "Khaki", hex: "#C3B091", stock: 26 }],
    countInStock: 26,
    isFeatured: true,
    isBestseller: false,
    sku: "PNT-CRG-012",
    weight: 750,
    dimensions: { length: 42, width: 32, height: 5 },
    meta: { title: "Cargo Pants", description: "Durable cargo pants for men." }
  },
  {
    name: "Formal Black Trousers",
    brand: "UrbanWear",
    description: "Stylish black trousers for formal occasions.",
    price: 1899,
    discountPrice: 1599,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318665/pant-4_zxpt39.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318665/pant-4_zxpt39.jpg", alt: "Formal Black Trousers" }],
    gender: "Men",
    type: "Pants",
    style: "Formal",
    season: "All-Season",
    tags: ["Trousers", "Formal", "Men"],
    sizes: [{ size: "M", stock: 6 }, { size: "L", stock: 8 }, { size: "XL", stock: 6 }],
    colors: [{ name: "Black", hex: "#000000", stock: 20 }],
    countInStock: 20,
    isFeatured: false,
    isBestseller: false,
    sku: "PNT-BLK-013",
    weight: 720,
    dimensions: { length: 42, width: 32, height: 5 },
    meta: { title: "Formal Black Trousers", description: "Classic black trousers for men." }
  },

  // --- SHIRTS ---
  {
    name: "White Cotton Shirt",
    brand: "UrbanWear",
    description: "Classic white cotton shirt for formal use.",
    price: 1299,
    discountPrice: 999,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318666/shirt-1_amw2uv.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318666/shirt-1_amw2uv.jpg", alt: "White Cotton Shirt" }],
    gender: "Men",
    type: "Shirt",
    style: "Formal",
    season: "All-Season",
    tags: ["Shirt", "Formal", "White"],
    sizes: [{ size: "M", stock: 10 }, { size: "L", stock: 12 }, { size: "XL", stock: 8 }],
    colors: [{ name: "White", hex: "#FFFFFF", stock: 30 }],
    countInStock: 30,
    isFeatured: true,
    isBestseller: true,
    sku: "SRT-WHT-014",
    weight: 400,
    dimensions: { length: 25, width: 20, height: 3 },
    meta: { title: "White Cotton Shirt", description: "Classic white cotton shirt for men." }
  },
  {
    name: "Blue Checked Shirt",
    brand: "Fashionista",
    description: "Trendy blue checked shirt for casual and office wear.",
    price: 1399,
    discountPrice: 1199,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318668/shirt-2_mzhn3s.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318668/shirt-2_mzhn3s.jpg", alt: "Blue Checked Shirt" }],
    gender: "Men",
    type: "Shirt",
    style: "Casual",
    season: "All-Season",
    tags: ["Checked", "Casual", "Blue"],
    sizes: [{ size: "M", stock: 9 }, { size: "L", stock: 11 }, { size: "XL", stock: 7 }],
    colors: [{ name: "Blue", hex: "#0000FF", stock: 27 }],
    countInStock: 27,
    isFeatured: false,
    isBestseller: true,
    sku: "SRT-BLU-015",
    weight: 420,
    dimensions: { length: 26, width: 21, height: 3 },
    meta: { title: "Blue Checked Shirt", description: "Blue checked shirt for casual and office wear." }
  },
  {
    name: "Black Formal Shirt",
    brand: "UrbanWear",
    description: "Stylish black shirt for formal events.",
    price: 1499,
    discountPrice: 1299,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318670/shirt-3_sjsgw2.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318670/shirt-3_sjsgw2.jpg", alt: "Black Formal Shirt" }],
    gender: "Men",
    type: "Shirt",
    style: "Formal",
    season: "All-Season",
    tags: ["Shirt", "Formal", "Black"],
    sizes: [{ size: "M", stock: 8 }, { size: "L", stock: 10 }, { size: "XL", stock: 6 }],
    colors: [{ name: "Black", hex: "#000000", stock: 24 }],
    countInStock: 24,
    isFeatured: false,
    isBestseller: false,
    sku: "SRT-BLK-016",
    weight: 430,
    dimensions: { length: 26, width: 21, height: 3 },
    meta: { title: "Black Formal Shirt", description: "Stylish black shirt for men." }
  },
  {
    name: "Casual Green Shirt",
    brand: "TrendyLook",
    description: "Casual green shirt for daily comfort.",
    price: 1199,
    discountPrice: 999,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318671/shirt-4_kred21.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318671/shirt-4_kred21.jpg", alt: "Casual Green Shirt" }],
    gender: "Men",
    type: "Shirt",
    style: "Casual",
    season: "All-Season",
    tags: ["Shirt", "Casual", "Green"],
    sizes: [{ size: "M", stock: 7 }, { size: "L", stock: 9 }, { size: "XL", stock: 6 }],
    colors: [{ name: "Green", hex: "#008000", stock: 22 }],
    countInStock: 22,
    isFeatured: true,
    isBestseller: false,
    sku: "SRT-GRN-017",
    weight: 410,
    dimensions: { length: 25, width: 20, height: 3 },
    meta: { title: "Casual Green Shirt", description: "Casual green shirt for men." }
  },

  // --- SHOES ---
  {
    name: "Running Shoes",
    brand: "SportyPro",
    description: "Comfortable running shoes with strong grip.",
    price: 2499,
    discountPrice: 2199,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318672/shoe-1_nh69hc.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318672/shoe-1_nh69hc.jpg", alt: "Running Shoes" }],
    gender: "Unisex",
    type: "Shoes",
    style: "Sportswear",
    season: "All-Season",
    tags: ["Shoes", "Running", "Sports"],
    sizes: [{ size: "M", stock: 10 }, { size: "L", stock: 12 }],
    colors: [{ name: "White", hex: "#FFFFFF", stock: 22 }],
    countInStock: 22,
    isFeatured: true,
    isBestseller: true,
    sku: "SHO-RUN-018",
    weight: 800,
    dimensions: { length: 32, width: 20, height: 12 },
    meta: { title: "Running Shoes", description: "Comfortable running shoes with grip." }
  },
  {
    name: "Casual Sneakers",
    brand: "UrbanWear",
    description: "Trendy sneakers for everyday comfort.",
    price: 2299,
    discountPrice: 1999,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318672/shoe-2_udnkzi.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318672/shoe-2_udnkzi.jpg", alt: "Casual Sneakers" }],
    gender: "Unisex",
    type: "Shoes",
    style: "Casual",
    season: "All-Season",
    tags: ["Shoes", "Casual", "Sneakers"],
    sizes: [{ size: "M", stock: 8 }, { size: "L", stock: 9 }, { size: "XL", stock: 5 }],
    colors: [{ name: "Grey", hex: "#808080", stock: 22 }],
    countInStock: 22,
    isFeatured: false,
    isBestseller: true,
    sku: "SHO-CAS-019",
    weight: 780,
    dimensions: { length: 31, width: 19, height: 12 },
    meta: { title: "Casual Sneakers", description: "Trendy sneakers for casual wear." }
  },
  {
    name: "Formal Leather Shoes",
    brand: "Fashionista",
    description: "Premium leather shoes for formal occasions.",
    price: 2799,
    discountPrice: 2499,
    imageUrl: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318673/shoe-3_gzyawx.jpg",
    images: [{ url: "https://res.cloudinary.com/dud1uoyvn/image/upload/v1759318673/shoe-3_gzyawx.jpg", alt: "Formal Leather Shoes" }],
    gender: "Men",
    type: "Shoes",
    style: "Formal",
    season: "All-Season",
    tags: ["Shoes", "Leather", "Formal"],
    sizes: [{ size: "M", stock: 6 }, { size: "L", stock: 8 }],
    colors: [{ name: "Brown", hex: "#8B4513", stock: 14 }],
    countInStock: 14,
    isFeatured: true,
    isBestseller: false,
    sku: "SHO-LEA-020",
    weight: 900,
    dimensions: { length: 33, width: 20, height: 12 },
    meta: { title: "Formal Leather Shoes", description: "Premium leather shoes for formal use." }
  }
];

const importData = async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log("✅ 20 Products Imported with all fields!");
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

importData();
